# Generated by Django 4.0.3 on 2022-04-20 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_paystack_token_transactionlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PayStackCustomer',
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
