# Generated by Django 4.0.3 on 2022-05-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_transactionlog_user_order_stripe_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_token',
            new_name='token',
        ),
    ]
